'use strict';
const assert=require('node:assert/strict'),{traceSort}=require('../algorithms');
const compare=(field,direction)=>(a,b)=>{let n=field==='name'?a.name.toLowerCase().localeCompare(b.name.toLowerCase(),'en'):a[field]-b[field];return direction==='asc'?n:-n;};
let checked=0;
function check(a,field,direction,algorithm){const before=JSON.stringify(a),r=traceSort(a,field,direction,algorithm),cmp=compare(field,direction);assert.equal(JSON.stringify(a),before,'Input must remain unchanged');assert.deepEqual(r.items.map(x=>x.id).sort((a,b)=>a-b),a.map(x=>x.id).sort((a,b)=>a-b));for(let i=1;i<r.items.length;i++)assert(cmp(r.items[i-1],r.items[i])<=0);assert.equal(r.events.at(-1).kind,'done');assert.deepEqual(r.events.at(-1).items,r.items);let lastC=0,lastM=0;for(const e of r.events){assert(e.comparisons>=lastC&&e.moves>=lastM);lastC=e.comparisons;lastM=e.moves;assert.deepEqual(e.items.map(x=>x.id).sort((a,b)=>a-b),a.map(x=>x.id).sort((a,b)=>a-b),'Every snapshot preserves all record identities');for(const x of e.items)assert.deepEqual(x,a.find(y=>y.id===x.id),'Fields remain attached to the record');if(e.output)for(let i=1;i<e.output.length;i++)assert(cmp(e.output[i-1],e.output[i])<=0,'Merge buffer remains sorted');}if(algorithm==='merge')assert.deepEqual(r.items,a.slice().sort(cmp),'Merge Sort must be stable');checked++;return r;}
let seed=8169;const rand=n=>{seed=(seed*1664525+1013904223)>>>0;return seed%n;};
for(let k=0;k<100;k++){const a=Array.from({length:rand(25)},(_,i)=>({id:i,name:['Pen','Notebook','Lamp','Bottle','pen'][rand(5)],price:rand(15)*12.5,stock:rand(20)}));for(const f of ['name','price','stock'])for(const d of ['asc','desc'])for(const alg of ['merge','quick'])check(a,f,d,alg);}
for(const n of [2,8,24]){const a=Array.from({length:n},(_,i)=>({id:i,name:'Item '+i,price:n-i,stock:i}));const r=check(a,'price','asc','quick');assert.equal(r.comparisons,n*(n-1)/2,'Last-element pivot has quadratic comparisons on reverse input');check(a,'price','asc','merge');}
const tied=[{id:0,name:'A',price:2,stock:3},{id:1,name:'B',price:2,stock:1},{id:2,name:'C',price:1,stock:2}];assert.deepEqual(check(tied,'price','asc','merge').items.map(x=>x.id),[2,0,1]);assert.deepEqual(check(tied,'price','asc','quick').items.map(x=>x.id),[2,1,0]);
assert.throws(()=>traceSort(tied,'unknown'));assert.throws(()=>traceSort(tied,'price','sideways'));assert.throws(()=>traceSort(tied,'price','asc','bubble'));
console.log(`PASS: ${checked} sorting cases across algorithms, fields, orders, snapshot identity preservation, ties, stability, boundaries, and quadratic worst-case comparisons.`);
